spring:
  datasource:
    driver-class-name: org.h2.Driver
<<<<<<< HEAD
    url: jdbc:h2:~/order;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
=======
    url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

>>>>>>> main
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
<<<<<<< HEAD
      hibernate.format_sql: true
=======
      hibernate.format_sql: true
  main:
    allow-bean-definition-overriding : true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


>>>>>>> main
